### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by fobo** [fobo/COSC381Scrumflow#1]
**User Story**
_As a student, I want to see my grades online so that I don't have to wait until I get to school to know my grades._

**Tasks**
- [ ] Create online grade viewer that can be accessed through the online portal.
- [ ] Interface must be easy to use and navigate
- [ ] Security measures to secure sensitive materials
- [ ] View is restricted to the registered student only

**Acceptance Criteria**
* Grade viewer is accessible through the online portal
* Students can view grades for courses and the overall GPA
* Accessible on Chrome, Firefox, and Safari web browsers
* Portal is secure to protect student information

**Acceptance Tests**
1. A student can view their grade/GPA
2. A student can login to the portal
3. A student can access the portal on major browser platforms

**Comment by fobo** [comment]
#1

**Comment by ciarawheeler** [comment]
Reviewed. Looks like you need to add a file to store the student information and their updated grades.

**Comment by eyu776** [comment]
> Reviewed. Looks like you need to add a file to store the student information and their updated grades.

@ciarawheeler 

In the future, pull request reviews should be done on the [pull request](https://github.com/fobo/COSC381Scrumflow/pull/2).
